[project]
name = "ivi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.3.5",
    "librosa>=0.10.2.post1",
    "numpy>=2.1.3",
]
